//Povray V3.1 code generated by Open Babel
//Author: Steffen Reith <streit@streit.cc>
//Version: $Id$
//Date: Thu Mar 13 18:08:45 CST 2003

//Include header for povray
#include "babel31.inc"

//Use PovRay3.1
#version 3.1;

//Print name of molecule while rendering
#render "\b\b pdb/TRP.pdb\n\n"

//Coodinates of atoms 1 - 14
#declare TRP_pos_1 = <19.46,15.407,20.116>;
#declare TRP_pos_2 = <19.487,16.872,20.001>;
#declare TRP_pos_3 = <20.257,17.06,18.688>;
#declare TRP_pos_4 = <21.389,17.543,18.677>;
#declare TRP_pos_5 = <20.213,17.541,21.187>;
#declare TRP_pos_6 = <19.679,17.185,22.548>;
#declare TRP_pos_7 = <20.234,16.472,23.573>;
#declare TRP_pos_8 = <18.389,17.594,23.039>;
#declare TRP_pos_9 = <19.374,16.376,24.633>;
#declare TRP_pos_10 = <18.215,17.033,24.316>;
#declare TRP_pos_11 = <17.341,18.325,22.442>;
#declare TRP_pos_12 = <17.036,17.198,25.043>;
#declare TRP_pos_13 = <16.177,18.528,23.189>;
#declare TRP_pos_14 = <16.026,17.948,24.45>;

//Povray-description of atoms 1 - 14
#declare TRP_atom1 = object {
	  Atom_N
	  translate TRP_pos_1
	 }
#declare TRP_atom2 = object {
	  Atom_C
	  translate TRP_pos_2
	 }
#declare TRP_atom3 = object {
	  Atom_C
	  translate TRP_pos_3
	 }
#declare TRP_atom4 = object {
	  Atom_O
	  translate TRP_pos_4
	 }
#declare TRP_atom5 = object {
	  Atom_C
	  translate TRP_pos_5
	 }
#declare TRP_atom6 = object {
	  Atom_C
	  translate TRP_pos_6
	 }
#declare TRP_atom7 = object {
	  Atom_C
	  translate TRP_pos_7
	 }
#declare TRP_atom8 = object {
	  Atom_C
	  translate TRP_pos_8
	 }
#declare TRP_atom9 = object {
	  Atom_N
	  translate TRP_pos_9
	 }
#declare TRP_atom10 = object {
	  Atom_C
	  translate TRP_pos_10
	 }
#declare TRP_atom11 = object {
	  Atom_C
	  translate TRP_pos_11
	 }
#declare TRP_atom12 = object {
	  Atom_C
	  translate TRP_pos_12
	 }
#declare TRP_atom13 = object {
	  Atom_C
	  translate TRP_pos_13
	 }
#declare TRP_atom14 = object {
	  Atom_C
	  translate TRP_pos_14
	 }

//Povray-description of bonds 1 - 15
#if (BAS)
#declare TRP_bond0 = object {
	  bond_1
	  scale <1.46975,1.0000,1.0000>
	  rotate <0.0000,0.0000,85.39>
	  rotate <0.0000,76.787,0.0000>
	  translate TRP_pos_1
	 }
#declare TRP_bond1 = object {
	  bond_1
	  scale <1.53369,1.0000,1.0000>
	  rotate <0.0000,0.0000,7.04102>
	  rotate <0.0000,59.6108,0.0000>
	  translate TRP_pos_2
	 }
#declare TRP_bond2 = object {
	  bond_1
	  scale <1.54313,1.0000,1.0000>
	  rotate <0.0000,0.0000,25.6922>
	  rotate <0.0000,-58.5275,0.0000>
	  translate TRP_pos_2
	 }
#declare TRP_bond3 = object {
	  bond_2
	  scale <1.23079,1.0000,1.0000>
	  rotate <0.0000,0.0000,23.1059>
	  rotate <0.0000,0.556545,0.0000>
	  translate TRP_pos_3
	 }
#declare TRP_bond4 = object {
	  bond_1
	  scale <1.50473,1.0000,1.0000>
	  rotate <0.0000,0.0000,-13.6852>
	  rotate <0.0000,-111.423,0.0000>
	  translate TRP_pos_5
	 }
#declare TRP_bond5 = object {
	  bond_2
	  scale <1.36639,1.0000,1.0000>
	  rotate <0.0000,0.0000,-31.454>
	  rotate <0.0000,-61.5661,0.0000>
	  translate TRP_pos_6
	 }
#declare TRP_bond6 = object {
	  bond_1
	  scale <1.43961,1.0000,1.0000>
	  rotate <0.0000,0.0000,16.5054>
	  rotate <0.0000,-159.162,0.0000>
	  translate TRP_pos_6
	 }
#declare TRP_bond7 = object {
	  bond_1
	  scale <1.36836,1.0000,1.0000>
	  rotate <0.0000,0.0000,-4.02302>
	  rotate <0.0000,-129.053,0.0000>
	  translate TRP_pos_7
	 }
#declare TRP_bond8 = object {
	  bond_1
	  scale <1.40561,1.0000,1.0000>
	  rotate <0.0000,0.0000,-23.5229>
	  rotate <0.0000,-97.7591,0.0000>
	  translate TRP_pos_8
	 }
#declare TRP_bond9 = object {
	  bond_2
	  scale <1.41035,1.0000,1.0000>
	  rotate <0.0000,0.0000,31.2192>
	  rotate <0.0000,150.332,0.0000>
	  translate TRP_pos_8
	 }
#declare TRP_bond10 = object {
	  bond_1
	  scale <1.36946,1.0000,1.0000>
	  rotate <0.0000,0.0000,28.6692>
	  rotate <0.0000,164.703,0.0000>
	  translate TRP_pos_9
	 }
#declare TRP_bond11 = object {
	  bond_2
	  scale <1.39492,1.0000,1.0000>
	  rotate <0.0000,0.0000,6.79318>
	  rotate <0.0000,-148.341,0.0000>
	  translate TRP_pos_10
	 }
#declare TRP_bond12 = object {
	  bond_1
	  scale <1.3979,1.0000,1.0000>
	  rotate <0.0000,0.0000,8.34989>
	  rotate <0.0000,-147.31,0.0000>
	  translate TRP_pos_11
	 }
#declare TRP_bond13 = object {
	  bond_1
	  scale <1.39077,1.0000,1.0000>
	  rotate <0.0000,0.0000,32.6339>
	  rotate <0.0000,149.582,0.0000>
	  translate TRP_pos_12
	 }
#declare TRP_bond14 = object {
	  bond_2
	  scale <1.39618,1.0000,1.0000>
	  rotate <0.0000,0.0000,-24.5457>
	  rotate <0.0000,-96.8285,0.0000>
	  translate TRP_pos_13
	 }
#end //(BAS-Bonds)

#if (CST)
#declare TRP_bond0 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Nam}
	    scale <0.734877,1.0000,1.0000>
	    rotate <0.0000,0.0000,85.39>
	    rotate <0.0000,76.787,0.0000>
	    translate TRP_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.734877,1.0000,1.0000>
	    rotate <0.0000,0.0000,265.39>
	    rotate <0.0000,76.787,0.0000>
	    translate TRP_pos_2
	   }
	  }
	 }

#declare TRP_bond1 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.766846,1.0000,1.0000>
	    rotate <0.0000,0.0000,7.04102>
	    rotate <0.0000,59.6108,0.0000>
	    translate TRP_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_Cac}
	    scale <0.766846,1.0000,1.0000>
	    rotate <0.0000,0.0000,187.041>
	    rotate <0.0000,59.6108,0.0000>
	    translate TRP_pos_3
	   }
	  }
	 }

#declare TRP_bond2 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.771563,1.0000,1.0000>
	    rotate <0.0000,0.0000,25.6922>
	    rotate <0.0000,-58.5275,0.0000>
	    translate TRP_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.771563,1.0000,1.0000>
	    rotate <0.0000,0.0000,205.692>
	    rotate <0.0000,-58.5275,0.0000>
	    translate TRP_pos_5
	   }
	  }
	 }

#declare TRP_bond3 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Cac}
	    scale <0.615393,1.0000,1.0000>
	    rotate <0.0000,0.0000,23.1059>
	    rotate <0.0000,0.556545,0.0000>
	    translate TRP_pos_3
	   }
	   object {
	    bond_2
	    pigment{color Color_O2}
	    scale <0.615393,1.0000,1.0000>
	    rotate <0.0000,0.0000,203.106>
	    rotate <0.0000,0.556545,0.0000>
	    translate TRP_pos_4
	   }
	  }
	 }

#declare TRP_bond4 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.752365,1.0000,1.0000>
	    rotate <0.0000,0.0000,-13.6852>
	    rotate <0.0000,-111.423,0.0000>
	    translate TRP_pos_5
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.752365,1.0000,1.0000>
	    rotate <0.0000,0.0000,166.315>
	    rotate <0.0000,-111.423,0.0000>
	    translate TRP_pos_6
	   }
	  }
	 }

#declare TRP_bond5 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.683194,1.0000,1.0000>
	    rotate <0.0000,0.0000,-31.454>
	    rotate <0.0000,-61.5661,0.0000>
	    translate TRP_pos_6
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.683194,1.0000,1.0000>
	    rotate <0.0000,0.0000,148.546>
	    rotate <0.0000,-61.5661,0.0000>
	    translate TRP_pos_7
	   }
	  }
	 }

#declare TRP_bond6 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.719803,1.0000,1.0000>
	    rotate <0.0000,0.0000,16.5054>
	    rotate <0.0000,-159.162,0.0000>
	    translate TRP_pos_6
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.719803,1.0000,1.0000>
	    rotate <0.0000,0.0000,196.505>
	    rotate <0.0000,-159.162,0.0000>
	    translate TRP_pos_8
	   }
	  }
	 }

#declare TRP_bond7 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.684181,1.0000,1.0000>
	    rotate <0.0000,0.0000,-4.02302>
	    rotate <0.0000,-129.053,0.0000>
	    translate TRP_pos_7
	   }
	   object {
	    bond_1
	    pigment{color Color_Nar}
	    scale <0.684181,1.0000,1.0000>
	    rotate <0.0000,0.0000,175.977>
	    rotate <0.0000,-129.053,0.0000>
	    translate TRP_pos_9
	   }
	  }
	 }

#declare TRP_bond8 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.702803,1.0000,1.0000>
	    rotate <0.0000,0.0000,-23.5229>
	    rotate <0.0000,-97.7591,0.0000>
	    translate TRP_pos_8
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.702803,1.0000,1.0000>
	    rotate <0.0000,0.0000,156.477>
	    rotate <0.0000,-97.7591,0.0000>
	    translate TRP_pos_10
	   }
	  }
	 }

#declare TRP_bond9 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.705173,1.0000,1.0000>
	    rotate <0.0000,0.0000,31.2192>
	    rotate <0.0000,150.332,0.0000>
	    translate TRP_pos_8
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.705173,1.0000,1.0000>
	    rotate <0.0000,0.0000,211.219>
	    rotate <0.0000,150.332,0.0000>
	    translate TRP_pos_11
	   }
	  }
	 }

#declare TRP_bond10 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Nar}
	    scale <0.68473,1.0000,1.0000>
	    rotate <0.0000,0.0000,28.6692>
	    rotate <0.0000,164.703,0.0000>
	    translate TRP_pos_9
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.68473,1.0000,1.0000>
	    rotate <0.0000,0.0000,208.669>
	    rotate <0.0000,164.703,0.0000>
	    translate TRP_pos_10
	   }
	  }
	 }

#declare TRP_bond11 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.697459,1.0000,1.0000>
	    rotate <0.0000,0.0000,6.79318>
	    rotate <0.0000,-148.341,0.0000>
	    translate TRP_pos_10
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.697459,1.0000,1.0000>
	    rotate <0.0000,0.0000,186.793>
	    rotate <0.0000,-148.341,0.0000>
	    translate TRP_pos_12
	   }
	  }
	 }

#declare TRP_bond12 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.698948,1.0000,1.0000>
	    rotate <0.0000,0.0000,8.34989>
	    rotate <0.0000,-147.31,0.0000>
	    translate TRP_pos_11
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.698948,1.0000,1.0000>
	    rotate <0.0000,0.0000,188.35>
	    rotate <0.0000,-147.31,0.0000>
	    translate TRP_pos_13
	   }
	  }
	 }

#declare TRP_bond13 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.695386,1.0000,1.0000>
	    rotate <0.0000,0.0000,32.6339>
	    rotate <0.0000,149.582,0.0000>
	    translate TRP_pos_12
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.695386,1.0000,1.0000>
	    rotate <0.0000,0.0000,212.634>
	    rotate <0.0000,149.582,0.0000>
	    translate TRP_pos_14
	   }
	  }
	 }

#declare TRP_bond14 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.698091,1.0000,1.0000>
	    rotate <0.0000,0.0000,-24.5457>
	    rotate <0.0000,-96.8285,0.0000>
	    translate TRP_pos_13
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.698091,1.0000,1.0000>
	    rotate <0.0000,0.0000,155.454>
	    rotate <0.0000,-96.8285,0.0000>
	    translate TRP_pos_14
	   }
	  }
	 }

#end // (CST-Bonds)


//All atoms of molecule TRP
#ifdef (TRANS)
#declare TRP_atoms = merge {
#else
#declare TRP_atoms = union {
#end //(End of TRANS)
	  object{TRP_atom1}
	  object{TRP_atom2}
	  object{TRP_atom3}
	  object{TRP_atom4}
	  object{TRP_atom5}
	  object{TRP_atom6}
	  object{TRP_atom7}
	  object{TRP_atom8}
	  object{TRP_atom9}
	  object{TRP_atom10}
	  object{TRP_atom11}
	  object{TRP_atom12}
	  object{TRP_atom13}
	  object{TRP_atom14}
	 }

//Bonds only needed for ball and sticks or capped sticks models
#if (BAS | CST)
#declare TRP_bonds = union {
	  object{TRP_bond0}
	  object{TRP_bond1}
	  object{TRP_bond2}
	  object{TRP_bond3}
	  object{TRP_bond4}
	  object{TRP_bond5}
	  object{TRP_bond6}
	  object{TRP_bond7}
	  object{TRP_bond8}
	  object{TRP_bond9}
	  object{TRP_bond10}
	  object{TRP_bond11}
	  object{TRP_bond12}
	  object{TRP_bond13}
	  object{TRP_bond14}
	 }
#end


//Definition of molecule TRP
#if (SPF)
#declare TRP = object{
	  TRP_atoms
#else
#declare TRP = union {
	  object{TRP_atoms}
#if (BAS | CST)//(Not really needed at moment!)
#if (TRANS)
	  difference {
	   object{TRP_bonds}
	   object{TRP_atoms}
	  }
#else
	  object{TRP_bonds}
#end //(End of TRANS)
#end //(End of (BAS|CST))
#end //(End of SPF)
//	  bounded_by {
//	   box {
//	    <-3,-3,-3>
//	    <24.389,21.528,28.043>
	 }

//Center of molecule TRP (bounding box)
#declare TRP_center = <-10.6945,-9.264,-12.5215>

