//Povray V3.1 code generated by Open Babel
//Author: Steffen Reith <streit@streit.cc>
//Version: $Id$
//Date: Fri Dec 06 19:50:04 CST 2002

//Include header for povray
#include "babel31.inc"

//Use PovRay3.1
#version 3.1;

//Print name of molecule while rendering
#render "\b\b Aromatic Test for Open Babel\n\n"

//Coodinates of atoms 1 - 48
#declare Aromatic_Test_for_Open_Babel_pos_1 = <0.6228,0.6666,0.1056>;
#declare Aromatic_Test_for_Open_Babel_pos_2 = <1.5924,-0.2475,0.2041>;
#declare Aromatic_Test_for_Open_Babel_pos_3 = <-0.7285,0.0995,0.1071>;
#declare Aromatic_Test_for_Open_Babel_pos_4 = <-0.7466,-1.2336,0.1472>;
#declare Aromatic_Test_for_Open_Babel_pos_5 = <5.0757,1.34,0.3648>;
#declare Aromatic_Test_for_Open_Babel_pos_6 = <5.8814,0.2825,0.2367>;
#declare Aromatic_Test_for_Open_Babel_pos_7 = <5.2756,-1.0486,0.0875>;
#declare Aromatic_Test_for_Open_Babel_pos_8 = <3.9476,-1.1925,0.0777>;
#declare Aromatic_Test_for_Open_Babel_pos_9 = <3.0535,-0.0291,0.2147>;
#declare Aromatic_Test_for_Open_Babel_pos_10 = <3.6131,1.178,0.3546>;
#declare Aromatic_Test_for_Open_Babel_pos_11 = <7.3459,0.4328,0.2468>;
#declare Aromatic_Test_for_Open_Babel_pos_12 = <8.1383,-0.5564,0.1745>;
#declare Aromatic_Test_for_Open_Babel_pos_13 = <9.2458,1.263,0.334>;
#declare Aromatic_Test_for_Open_Babel_pos_14 = <9.4356,0.0111,0.2344>;
#declare Aromatic_Test_for_Open_Babel_pos_15 = <0.906,-1.9031,0.2452>;
#declare Aromatic_Test_for_Open_Babel_pos_16 = <0.8589,1.9705,-0.0336>;
#declare Aromatic_Test_for_Open_Babel_pos_17 = <-0.3229,2.6613,-0.4594>;
#declare Aromatic_Test_for_Open_Babel_pos_18 = <-1.5231,2.2148,0.394>;
#declare Aromatic_Test_for_Open_Babel_pos_19 = <-1.833,0.8456,0.1065>;
#declare Aromatic_Test_for_Open_Babel_pos_20 = <7.9607,1.609,0.343>;
#declare Aromatic_Test_for_Open_Babel_pos_21 = <-1.9718,-2.1059,0.1766>;
#declare Aromatic_Test_for_Open_Babel_pos_22 = <-3.1905,-1.314,0.0644>;
#declare Aromatic_Test_for_Open_Babel_pos_23 = <-4.1934,-0.654,-0.0288>;
#declare Aromatic_Test_for_Open_Babel_pos_24 = <-5.4062,0.1506,-0.1464>;
#declare Aromatic_Test_for_Open_Babel_pos_25 = <-6.6818,-0.6915,0.2144>;
#declare Aromatic_Test_for_Open_Babel_pos_26 = <-5.2493,1.0537,0.4856>;
#declare Aromatic_Test_for_Open_Babel_pos_27 = <-6.8934,-1.5654,-0.5106>;
#declare Aromatic_Test_for_Open_Babel_pos_28 = <-7.5642,-0.0087,0.2444>;
#declare Aromatic_Test_for_Open_Babel_pos_29 = <-7.865,-2.0694,-0.2058>;
#declare Aromatic_Test_for_Open_Babel_pos_30 = <-7.0205,-1.1265,-1.5424>;
#declare Aromatic_Test_for_Open_Babel_pos_31 = <-6.0314,-2.3022,-0.5358>;
#declare Aromatic_Test_for_Open_Babel_pos_32 = <5.4954,2.3088,0.4751>;
#declare Aromatic_Test_for_Open_Babel_pos_33 = <5.8984,-1.9023,-0.0132>;
#declare Aromatic_Test_for_Open_Babel_pos_34 = <3.529,-2.1619,-0.0308>;
#declare Aromatic_Test_for_Open_Babel_pos_35 = <2.9922,2.0325,0.4601>;
#declare Aromatic_Test_for_Open_Babel_pos_36 = <10.0374,1.9669,0.4036>;
#declare Aromatic_Test_for_Open_Babel_pos_37 = <-0.1746,3.745,-0.3427>;
#declare Aromatic_Test_for_Open_Babel_pos_38 = <-0.5205,2.4262,-1.5157>;
#declare Aromatic_Test_for_Open_Babel_pos_39 = <-1.2729,2.3176,1.4602>;
#declare Aromatic_Test_for_Open_Babel_pos_40 = <-2.3939,2.8442,0.1584>;
#declare Aromatic_Test_for_Open_Babel_pos_41 = <7.5606,2.5179,0.4058>;
#declare Aromatic_Test_for_Open_Babel_pos_42 = <-1.9269,-2.8148,-0.6633>;
#declare Aromatic_Test_for_Open_Babel_pos_43 = <-1.9934,-2.6407,1.1377>;
#declare Aromatic_Test_for_Open_Babel_pos_44 = <-5.5937,0.4757,-1.1804>;
#declare Aromatic_Test_for_Open_Babel_pos_45 = <-6.4912,-1.1532,1.1945>;
#declare Aromatic_Test_for_Open_Babel_pos_46 = <-7.7526,-3.0524,-0.2411>;
#declare Aromatic_Test_for_Open_Babel_pos_47 = <-7.985,-1.0391,-1.7478>;
#declare Aromatic_Test_for_Open_Babel_pos_48 = <-6.3862,-3.2264,-0.5255>;

//Povray-description of atoms 1 - 48
#declare Aromatic_Test_for_Open_Babel_atom1 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_1
	 }
#declare Aromatic_Test_for_Open_Babel_atom2 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_2
	 }
#declare Aromatic_Test_for_Open_Babel_atom3 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_3
	 }
#declare Aromatic_Test_for_Open_Babel_atom4 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_4
	 }
#declare Aromatic_Test_for_Open_Babel_atom5 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_5
	 }
#declare Aromatic_Test_for_Open_Babel_atom6 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_6
	 }
#declare Aromatic_Test_for_Open_Babel_atom7 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_7
	 }
#declare Aromatic_Test_for_Open_Babel_atom8 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_8
	 }
#declare Aromatic_Test_for_Open_Babel_atom9 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_9
	 }
#declare Aromatic_Test_for_Open_Babel_atom10 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_10
	 }
#declare Aromatic_Test_for_Open_Babel_atom11 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_11
	 }
#declare Aromatic_Test_for_Open_Babel_atom12 = object {
	  Atom_N
	  translate Aromatic_Test_for_Open_Babel_pos_12
	 }
#declare Aromatic_Test_for_Open_Babel_atom13 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_13
	 }
#declare Aromatic_Test_for_Open_Babel_atom14 = object {
	  Atom_N
	  translate Aromatic_Test_for_Open_Babel_pos_14
	 }
#declare Aromatic_Test_for_Open_Babel_atom15 = object {
	  Atom_S
	  translate Aromatic_Test_for_Open_Babel_pos_15
	 }
#declare Aromatic_Test_for_Open_Babel_atom16 = object {
	  Atom_O
	  translate Aromatic_Test_for_Open_Babel_pos_16
	 }
#declare Aromatic_Test_for_Open_Babel_atom17 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_17
	 }
#declare Aromatic_Test_for_Open_Babel_atom18 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_18
	 }
#declare Aromatic_Test_for_Open_Babel_atom19 = object {
	  Atom_O
	  translate Aromatic_Test_for_Open_Babel_pos_19
	 }
#declare Aromatic_Test_for_Open_Babel_atom20 = object {
	  Atom_N
	  translate Aromatic_Test_for_Open_Babel_pos_20
	 }
#declare Aromatic_Test_for_Open_Babel_atom21 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_21
	 }
#declare Aromatic_Test_for_Open_Babel_atom22 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_22
	 }
#declare Aromatic_Test_for_Open_Babel_atom23 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_23
	 }
#declare Aromatic_Test_for_Open_Babel_atom24 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_24
	 }
#declare Aromatic_Test_for_Open_Babel_atom25 = object {
	  Atom_C
	  translate Aromatic_Test_for_Open_Babel_pos_25
	 }
#declare Aromatic_Test_for_Open_Babel_atom26 = object {
	  Atom_I
	  translate Aromatic_Test_for_Open_Babel_pos_26
	 }
#declare Aromatic_Test_for_Open_Babel_atom27 = object {
	  Atom_Si
	  translate Aromatic_Test_for_Open_Babel_pos_27
	 }
#declare Aromatic_Test_for_Open_Babel_atom28 = object {
	  Atom_Rb
	  translate Aromatic_Test_for_Open_Babel_pos_28
	 }
#declare Aromatic_Test_for_Open_Babel_atom29 = object {
	  Atom_O
	  translate Aromatic_Test_for_Open_Babel_pos_29
	 }
#declare Aromatic_Test_for_Open_Babel_atom30 = object {
	  Atom_O
	  translate Aromatic_Test_for_Open_Babel_pos_30
	 }
#declare Aromatic_Test_for_Open_Babel_atom31 = object {
	  Atom_O
	  translate Aromatic_Test_for_Open_Babel_pos_31
	 }
#declare Aromatic_Test_for_Open_Babel_atom32 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_32
	 }
#declare Aromatic_Test_for_Open_Babel_atom33 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_33
	 }
#declare Aromatic_Test_for_Open_Babel_atom34 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_34
	 }
#declare Aromatic_Test_for_Open_Babel_atom35 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_35
	 }
#declare Aromatic_Test_for_Open_Babel_atom36 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_36
	 }
#declare Aromatic_Test_for_Open_Babel_atom37 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_37
	 }
#declare Aromatic_Test_for_Open_Babel_atom38 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_38
	 }
#declare Aromatic_Test_for_Open_Babel_atom39 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_39
	 }
#declare Aromatic_Test_for_Open_Babel_atom40 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_40
	 }
#declare Aromatic_Test_for_Open_Babel_atom41 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_41
	 }
#declare Aromatic_Test_for_Open_Babel_atom42 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_42
	 }
#declare Aromatic_Test_for_Open_Babel_atom43 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_43
	 }
#declare Aromatic_Test_for_Open_Babel_atom44 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_44
	 }
#declare Aromatic_Test_for_Open_Babel_atom45 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_45
	 }
#declare Aromatic_Test_for_Open_Babel_atom46 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_46
	 }
#declare Aromatic_Test_for_Open_Babel_atom47 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_47
	 }
#declare Aromatic_Test_for_Open_Babel_atom48 = object {
	  Atom_H
	  translate Aromatic_Test_for_Open_Babel_pos_48
	 }

//Povray-description of bonds 1 - 51
#if (BAS)
#declare Aromatic_Test_for_Open_Babel_bond0 = object {
	  bond_2
	  scale <1.33619,1.0000,1.0000>
	  rotate <0.0000,0.0000,-43.1656>
	  rotate <0.0000,-5.80069,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_1
	 }
#declare Aromatic_Test_for_Open_Babel_bond1 = object {
	  bond_2
	  scale <1.33383,1.0000,1.0000>
	  rotate <0.0000,0.0000,-88.1098>
	  rotate <0.0000,-114.293,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_3
	 }
#declare Aromatic_Test_for_Open_Babel_bond2 = object {
	  bond_2
	  scale <1.33562,1.0000,1.0000>
	  rotate <0.0000,0.0000,-52.3512>
	  rotate <0.0000,9.03394,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_5
	 }
#declare Aromatic_Test_for_Open_Babel_bond3 = object {
	  bond_2
	  scale <1.33581,1.0000,1.0000>
	  rotate <0.0000,0.0000,-6.18418>
	  rotate <0.0000,179.578,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_7
	 }
#declare Aromatic_Test_for_Open_Babel_bond4 = object {
	  bond_2
	  scale <1.33784,1.0000,1.0000>
	  rotate <0.0000,0.0000,64.4588>
	  rotate <0.0000,-14.0362,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_9
	 }
#declare Aromatic_Test_for_Open_Babel_bond5 = object {
	  bond_2
	  scale <1.2695,1.0000,1.0000>
	  rotate <0.0000,0.0000,-51.1875>
	  rotate <0.0000,5.21335,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_11
	 }
#declare Aromatic_Test_for_Open_Babel_bond6 = object {
	  bond_2
	  scale <1.27012,1.0000,1.0000>
	  rotate <0.0000,0.0000,-80.2842>
	  rotate <0.0000,27.6888,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_13
	 }
#declare Aromatic_Test_for_Open_Babel_bond7 = object {
	  bond_1
	  scale <1.79272,1.0000,1.0000>
	  rotate <0.0000,0.0000,-67.4452>
	  rotate <0.0000,-176.573,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_2
	 }
#declare Aromatic_Test_for_Open_Babel_bond8 = object {
	  bond_1
	  scale <1.78576,1.0000,1.0000>
	  rotate <0.0000,0.0000,22.0188>
	  rotate <0.0000,176.606,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_15
	 }
#declare Aromatic_Test_for_Open_Babel_bond9 = object {
	  bond_1
	  scale <1.46547,1.0000,1.0000>
	  rotate <0.0000,0.0000,-22.7663>
	  rotate <0.0000,-179.937,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_1
	 }
#declare Aromatic_Test_for_Open_Babel_bond10 = object {
	  bond_1
	  scale <1.33239,1.0000,1.0000>
	  rotate <0.0000,0.0000,78.1292>
	  rotate <0.0000,30.5228,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_1
	 }
#declare Aromatic_Test_for_Open_Babel_bond11 = object {
	  bond_1
	  scale <1.43358,1.0000,1.0000>
	  rotate <0.0000,0.0000,28.8076>
	  rotate <0.0000,160.186,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_16
	 }
#declare Aromatic_Test_for_Open_Babel_bond12 = object {
	  bond_1
	  scale <1.53887,1.0000,1.0000>
	  rotate <0.0000,0.0000,-16.8668>
	  rotate <0.0000,-144.585,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_17
	 }
#declare Aromatic_Test_for_Open_Babel_bond13 = object {
	  bond_1
	  scale <1.43297,1.0000,1.0000>
	  rotate <0.0000,0.0000,-72.8426>
	  rotate <0.0000,137.147,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_18
	 }
#declare Aromatic_Test_for_Open_Babel_bond14 = object {
	  bond_1
	  scale <1.33289,1.0000,1.0000>
	  rotate <0.0000,0.0000,-34.0394>
	  rotate <0.0000,-0.0395647,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_19
	 }
#declare Aromatic_Test_for_Open_Babel_bond15 = object {
	  bond_1
	  scale <1.47737,1.0000,1.0000>
	  rotate <0.0000,0.0000,-8.5012>
	  rotate <0.0000,179.584,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_9
	 }
#declare Aromatic_Test_for_Open_Babel_bond16 = object {
	  bond_1
	  scale <1.47366,1.0000,1.0000>
	  rotate <0.0000,0.0000,-52.1352>
	  rotate <0.0000,8.71149,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_9
	 }
#declare Aromatic_Test_for_Open_Babel_bond17 = object {
	  bond_1
	  scale <1.47006,1.0000,1.0000>
	  rotate <0.0000,0.0000,-64.8869>
	  rotate <0.0000,166.164,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_6
	 }
#declare Aromatic_Test_for_Open_Babel_bond18 = object {
	  bond_1
	  scale <1.47158,1.0000,1.0000>
	  rotate <0.0000,0.0000,-6.32026>
	  rotate <0.0000,179.601,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_5
	 }
#declare Aromatic_Test_for_Open_Babel_bond19 = object {
	  bond_1
	  scale <1.47223,1.0000,1.0000>
	  rotate <0.0000,0.0000,5.85955>
	  rotate <0.0000,-0.395153,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_6
	 }
#declare Aromatic_Test_for_Open_Babel_bond20 = object {
	  bond_1
	  scale <1.41726,1.0000,1.0000>
	  rotate <0.0000,0.0000,-23.6044>
	  rotate <0.0000,177.356,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_14
	 }
#declare Aromatic_Test_for_Open_Babel_bond21 = object {
	  bond_1
	  scale <1.33089,1.0000,1.0000>
	  rotate <0.0000,0.0000,15.0686>
	  rotate <0.0000,-179.599,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_13
	 }
#declare Aromatic_Test_for_Open_Babel_bond22 = object {
	  bond_1
	  scale <1.33067,1.0000,1.0000>
	  rotate <0.0000,0.0000,-62.1185>
	  rotate <0.0000,171.107,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_20
	 }
#declare Aromatic_Test_for_Open_Babel_bond23 = object {
	  bond_1
	  scale <1.50429,1.0000,1.0000>
	  rotate <0.0000,0.0000,-35.4418>
	  rotate <0.0000,-178.625,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_4
	 }
#declare Aromatic_Test_for_Open_Babel_bond24 = object {
	  bond_1
	  scale <1.45771,1.0000,1.0000>
	  rotate <0.0000,0.0000,32.9051>
	  rotate <0.0000,174.74,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_21
	 }
#declare Aromatic_Test_for_Open_Babel_bond25 = object {
	  bond_3
	  scale <1.2042,1.0000,1.0000>
	  rotate <0.0000,0.0000,33.2355>
	  rotate <0.0000,174.691,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_22
	 }
#declare Aromatic_Test_for_Open_Babel_bond26 = object {
	  bond_1
	  scale <1.46017,1.0000,1.0000>
	  rotate <0.0000,0.0000,33.4378>
	  rotate <0.0000,174.462,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_23
	 }
#declare Aromatic_Test_for_Open_Babel_bond27 = object {
	  bond_1
	  scale <1.5705,1.0000,1.0000>
	  rotate <0.0000,0.0000,-32.4253>
	  rotate <0.0000,-164.207,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_24
	 }
#declare Aromatic_Test_for_Open_Babel_bond28 = object {
	  bond_1
	  scale <1.11339,1.0000,1.0000>
	  rotate <0.0000,0.0000,54.2063>
	  rotate <0.0000,-76.0577,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_24
	 }
#declare Aromatic_Test_for_Open_Babel_bond29 = object {
	  bond_1
	  scale <1.15503,1.0000,1.0000>
	  rotate <0.0000,0.0000,-49.1655>
	  rotate <0.0000,106.271,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_25
	 }
#declare Aromatic_Test_for_Open_Babel_bond30 = object {
	  bond_1
	  scale <1.11613,1.0000,1.0000>
	  rotate <0.0000,0.0000,37.7166>
	  rotate <0.0000,-178.053,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_25
	 }
#declare Aromatic_Test_for_Open_Babel_bond31 = object {
	  bond_1
	  scale <1.13619,1.0000,1.0000>
	  rotate <0.0000,0.0000,-26.333>
	  rotate <0.0000,-162.583,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_27
	 }
#declare Aromatic_Test_for_Open_Babel_bond32 = object {
	  bond_1
	  scale <1.12845,1.0000,1.0000>
	  rotate <0.0000,0.0000,22.8886>
	  rotate <0.0000,97.0225,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_27
	 }
#declare Aromatic_Test_for_Open_Babel_bond33 = object {
	  bond_1
	  scale <1.13426,1.0000,1.0000>
	  rotate <0.0000,0.0000,-40.5103>
	  rotate <0.0000,1.67456,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_27
	 }
#declare Aromatic_Test_for_Open_Babel_bond34 = object {
	  bond_1
	  scale <1.06155,1.0000,1.0000>
	  rotate <0.0000,0.0000,65.8711>
	  rotate <0.0000,-14.7247,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_5
	 }
#declare Aromatic_Test_for_Open_Babel_bond35 = object {
	  bond_1
	  scale <1.06152,1.0000,1.0000>
	  rotate <0.0000,0.0000,-53.5354>
	  rotate <0.0000,9.18461,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_7
	 }
#declare Aromatic_Test_for_Open_Babel_bond36 = object {
	  bond_1
	  scale <1.06148,1.0000,1.0000>
	  rotate <0.0000,0.0000,-65.9592>
	  rotate <0.0000,165.469,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_8
	 }
#declare Aromatic_Test_for_Open_Babel_bond37 = object {
	  bond_1
	  scale <1.06152,1.0000,1.0000>
	  rotate <0.0000,0.0000,53.6084>
	  rotate <0.0000,-170.357,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_10
	 }
#declare Aromatic_Test_for_Open_Babel_bond38 = object {
	  bond_1
	  scale <1.06158,1.0000,1.0000>
	  rotate <0.0000,0.0000,41.5343>
	  rotate <0.0000,-5.02473,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_13
	 }
#declare Aromatic_Test_for_Open_Babel_bond39 = object {
	  bond_1
	  scale <1.10001,1.0000,1.0000>
	  rotate <0.0000,0.0000,80.1218>
	  rotate <0.0000,-38.1999,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_17
	 }
#declare Aromatic_Test_for_Open_Babel_bond40 = object {
	  bond_1
	  scale <1.10004,1.0000,1.0000>
	  rotate <0.0000,0.0000,-12.3404>
	  rotate <0.0000,100.596,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_17
	 }
#declare Aromatic_Test_for_Open_Babel_bond41 = object {
	  bond_1
	  scale <1.09998,1.0000,1.0000>
	  rotate <0.0000,0.0000,5.3625>
	  rotate <0.0000,-76.7936,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_18
	 }
#declare Aromatic_Test_for_Open_Babel_bond42 = object {
	  bond_1
	  scale <1.09997,1.0000,1.0000>
	  rotate <0.0000,0.0000,34.9034>
	  rotate <0.0000,164.861,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_18
	 }
#declare Aromatic_Test_for_Open_Babel_bond43 = object {
	  bond_1
	  scale <0.995049,1.0000,1.0000>
	  rotate <0.0000,0.0000,65.9826>
	  rotate <0.0000,-171.08,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_20
	 }
#declare Aromatic_Test_for_Open_Babel_bond44 = object {
	  bond_1
	  scale <1.09999,1.0000,1.0000>
	  rotate <0.0000,0.0000,-40.125>
	  rotate <0.0000,86.94,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_21
	 }
#declare Aromatic_Test_for_Open_Babel_bond45 = object {
	  bond_1
	  scale <1.10009,1.0000,1.0000>
	  rotate <0.0000,0.0000,-29.0874>
	  rotate <0.0000,-91.2875,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_21
	 }
#declare Aromatic_Test_for_Open_Babel_bond46 = object {
	  bond_1
	  scale <1.1,1.0000,1.0000>
	  rotate <0.0000,0.0000,17.1902>
	  rotate <0.0000,100.278,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_24
	 }
#declare Aromatic_Test_for_Open_Babel_bond47 = object {
	  bond_1
	  scale <1.10004,1.0000,1.0000>
	  rotate <0.0000,0.0000,-24.8164>
	  rotate <0.0000,-78.9951,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_25
	 }
#declare Aromatic_Test_for_Open_Babel_bond48 = object {
	  bond_1
	  scale <0.990035,1.0000,1.0000>
	  rotate <0.0000,0.0000,-83.1657>
	  rotate <0.0000,17.4353,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_29
	 }
#declare Aromatic_Test_for_Open_Babel_bond49 = object {
	  bond_1
	  scale <0.989994,1.0000,1.0000>
	  rotate <0.0000,0.0000,5.06486>
	  rotate <0.0000,167.978,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_30
	 }
#declare Aromatic_Test_for_Open_Babel_bond50 = object {
	  bond_1
	  scale <0.990017,1.0000,1.0000>
	  rotate <0.0000,0.0000,-68.9902>
	  rotate <0.0000,-178.337,0.0000>
	  translate Aromatic_Test_for_Open_Babel_pos_31
	 }
#end //(BAS-Bonds)

#if (CST)
#declare Aromatic_Test_for_Open_Babel_bond0 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.668095,1.0000,1.0000>
	    rotate <0.0000,0.0000,-43.1656>
	    rotate <0.0000,-5.80069,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_1
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.668095,1.0000,1.0000>
	    rotate <0.0000,0.0000,136.834>
	    rotate <0.0000,-5.80069,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_2
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond1 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.666913,1.0000,1.0000>
	    rotate <0.0000,0.0000,-88.1098>
	    rotate <0.0000,-114.293,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_3
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.666913,1.0000,1.0000>
	    rotate <0.0000,0.0000,91.8902>
	    rotate <0.0000,-114.293,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_4
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond2 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.667808,1.0000,1.0000>
	    rotate <0.0000,0.0000,-52.3512>
	    rotate <0.0000,9.03394,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_5
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.667808,1.0000,1.0000>
	    rotate <0.0000,0.0000,127.649>
	    rotate <0.0000,9.03394,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_6
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond3 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.667905,1.0000,1.0000>
	    rotate <0.0000,0.0000,-6.18418>
	    rotate <0.0000,179.578,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_7
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.667905,1.0000,1.0000>
	    rotate <0.0000,0.0000,173.816>
	    rotate <0.0000,179.578,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_8
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond4 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.66892,1.0000,1.0000>
	    rotate <0.0000,0.0000,64.4588>
	    rotate <0.0000,-14.0362,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_9
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.66892,1.0000,1.0000>
	    rotate <0.0000,0.0000,244.459>
	    rotate <0.0000,-14.0362,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_10
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond5 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.634752,1.0000,1.0000>
	    rotate <0.0000,0.0000,-51.1875>
	    rotate <0.0000,5.21335,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_11
	   }
	   object {
	    bond_2
	    pigment{color Color_Nar}
	    scale <0.634752,1.0000,1.0000>
	    rotate <0.0000,0.0000,128.812>
	    rotate <0.0000,5.21335,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_12
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond6 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.635059,1.0000,1.0000>
	    rotate <0.0000,0.0000,-80.2842>
	    rotate <0.0000,27.6888,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_13
	   }
	   object {
	    bond_2
	    pigment{color Color_Nar}
	    scale <0.635059,1.0000,1.0000>
	    rotate <0.0000,0.0000,99.7158>
	    rotate <0.0000,27.6888,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_14
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond7 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.89636,1.0000,1.0000>
	    rotate <0.0000,0.0000,-67.4452>
	    rotate <0.0000,-176.573,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_S2}
	    scale <0.89636,1.0000,1.0000>
	    rotate <0.0000,0.0000,112.555>
	    rotate <0.0000,-176.573,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_15
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond8 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_S2}
	    scale <0.892878,1.0000,1.0000>
	    rotate <0.0000,0.0000,22.0188>
	    rotate <0.0000,176.606,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_15
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.892878,1.0000,1.0000>
	    rotate <0.0000,0.0000,202.019>
	    rotate <0.0000,176.606,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_4
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond9 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.732737,1.0000,1.0000>
	    rotate <0.0000,0.0000,-22.7663>
	    rotate <0.0000,-179.937,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.732737,1.0000,1.0000>
	    rotate <0.0000,0.0000,157.234>
	    rotate <0.0000,-179.937,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_3
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond10 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.666197,1.0000,1.0000>
	    rotate <0.0000,0.0000,78.1292>
	    rotate <0.0000,30.5228,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_O2}
	    scale <0.666197,1.0000,1.0000>
	    rotate <0.0000,0.0000,258.129>
	    rotate <0.0000,30.5228,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_16
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond11 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O2}
	    scale <0.716792,1.0000,1.0000>
	    rotate <0.0000,0.0000,28.8076>
	    rotate <0.0000,160.186,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_16
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.716792,1.0000,1.0000>
	    rotate <0.0000,0.0000,208.808>
	    rotate <0.0000,160.186,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_17
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond12 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.769437,1.0000,1.0000>
	    rotate <0.0000,0.0000,-16.8668>
	    rotate <0.0000,-144.585,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_17
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.769437,1.0000,1.0000>
	    rotate <0.0000,0.0000,163.133>
	    rotate <0.0000,-144.585,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_18
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond13 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.716485,1.0000,1.0000>
	    rotate <0.0000,0.0000,-72.8426>
	    rotate <0.0000,137.147,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_18
	   }
	   object {
	    bond_1
	    pigment{color Color_O2}
	    scale <0.716485,1.0000,1.0000>
	    rotate <0.0000,0.0000,107.157>
	    rotate <0.0000,137.147,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_19
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond14 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O2}
	    scale <0.666443,1.0000,1.0000>
	    rotate <0.0000,0.0000,-34.0394>
	    rotate <0.0000,-0.0395647,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_19
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.666443,1.0000,1.0000>
	    rotate <0.0000,0.0000,145.961>
	    rotate <0.0000,-0.0395647,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_3
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond15 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.738685,1.0000,1.0000>
	    rotate <0.0000,0.0000,-8.5012>
	    rotate <0.0000,179.584,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_9
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.738685,1.0000,1.0000>
	    rotate <0.0000,0.0000,171.499>
	    rotate <0.0000,179.584,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_2
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond16 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.736832,1.0000,1.0000>
	    rotate <0.0000,0.0000,-52.1352>
	    rotate <0.0000,8.71149,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_9
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.736832,1.0000,1.0000>
	    rotate <0.0000,0.0000,127.865>
	    rotate <0.0000,8.71149,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_8
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond17 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.735031,1.0000,1.0000>
	    rotate <0.0000,0.0000,-64.8869>
	    rotate <0.0000,166.164,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_6
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.735031,1.0000,1.0000>
	    rotate <0.0000,0.0000,115.113>
	    rotate <0.0000,166.164,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_7
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond18 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.73579,1.0000,1.0000>
	    rotate <0.0000,0.0000,-6.32026>
	    rotate <0.0000,179.601,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_5
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.73579,1.0000,1.0000>
	    rotate <0.0000,0.0000,173.68>
	    rotate <0.0000,179.601,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_10
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond19 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.736113,1.0000,1.0000>
	    rotate <0.0000,0.0000,5.85955>
	    rotate <0.0000,-0.395153,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_6
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.736113,1.0000,1.0000>
	    rotate <0.0000,0.0000,185.86>
	    rotate <0.0000,-0.395153,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_11
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond20 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Nar}
	    scale <0.708631,1.0000,1.0000>
	    rotate <0.0000,0.0000,-23.6044>
	    rotate <0.0000,177.356,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_14
	   }
	   object {
	    bond_1
	    pigment{color Color_Nar}
	    scale <0.708631,1.0000,1.0000>
	    rotate <0.0000,0.0000,156.396>
	    rotate <0.0000,177.356,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_12
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond21 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.665447,1.0000,1.0000>
	    rotate <0.0000,0.0000,15.0686>
	    rotate <0.0000,-179.599,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_13
	   }
	   object {
	    bond_1
	    pigment{color Color_Nar}
	    scale <0.665447,1.0000,1.0000>
	    rotate <0.0000,0.0000,195.069>
	    rotate <0.0000,-179.599,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_20
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond22 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Nar}
	    scale <0.665334,1.0000,1.0000>
	    rotate <0.0000,0.0000,-62.1185>
	    rotate <0.0000,171.107,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_20
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.665334,1.0000,1.0000>
	    rotate <0.0000,0.0000,117.882>
	    rotate <0.0000,171.107,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_11
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond23 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.752145,1.0000,1.0000>
	    rotate <0.0000,0.0000,-35.4418>
	    rotate <0.0000,-178.625,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_4
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.752145,1.0000,1.0000>
	    rotate <0.0000,0.0000,144.558>
	    rotate <0.0000,-178.625,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_21
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond24 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.728856,1.0000,1.0000>
	    rotate <0.0000,0.0000,32.9051>
	    rotate <0.0000,174.74,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_21
	   }
	   object {
	    bond_1
	    pigment{color Color_C1}
	    scale <0.728856,1.0000,1.0000>
	    rotate <0.0000,0.0000,212.905>
	    rotate <0.0000,174.74,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_22
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond25 = object {
	  union {
	   object {
	    bond_3
	    pigment{color Color_C1}
	    scale <0.602099,1.0000,1.0000>
	    rotate <0.0000,0.0000,33.2355>
	    rotate <0.0000,174.691,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_22
	   }
	   object {
	    bond_3
	    pigment{color Color_C1}
	    scale <0.602099,1.0000,1.0000>
	    rotate <0.0000,0.0000,213.236>
	    rotate <0.0000,174.691,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_23
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond26 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C1}
	    scale <0.730085,1.0000,1.0000>
	    rotate <0.0000,0.0000,33.4378>
	    rotate <0.0000,174.462,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_23
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.730085,1.0000,1.0000>
	    rotate <0.0000,0.0000,213.438>
	    rotate <0.0000,174.462,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_24
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond27 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.785249,1.0000,1.0000>
	    rotate <0.0000,0.0000,-32.4253>
	    rotate <0.0000,-164.207,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_24
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.785249,1.0000,1.0000>
	    rotate <0.0000,0.0000,147.575>
	    rotate <0.0000,-164.207,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_25
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond28 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.556694,1.0000,1.0000>
	    rotate <0.0000,0.0000,54.2063>
	    rotate <0.0000,-76.0577,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_24
	   }
	   object {
	    bond_1
	    pigment{color Color_I}
	    scale <0.556694,1.0000,1.0000>
	    rotate <0.0000,0.0000,234.206>
	    rotate <0.0000,-76.0577,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_26
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond29 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.577516,1.0000,1.0000>
	    rotate <0.0000,0.0000,-49.1655>
	    rotate <0.0000,106.271,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_25
	   }
	   object {
	    bond_1
	    pigment{color Color_Si}
	    scale <0.577516,1.0000,1.0000>
	    rotate <0.0000,0.0000,130.834>
	    rotate <0.0000,106.271,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_27
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond30 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.558065,1.0000,1.0000>
	    rotate <0.0000,0.0000,37.7166>
	    rotate <0.0000,-178.053,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_25
	   }
	   object {
	    bond_1
	    pigment{color Color_Rb}
	    scale <0.558065,1.0000,1.0000>
	    rotate <0.0000,0.0000,217.717>
	    rotate <0.0000,-178.053,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_28
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond31 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Si}
	    scale <0.568094,1.0000,1.0000>
	    rotate <0.0000,0.0000,-26.333>
	    rotate <0.0000,-162.583,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_27
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.568094,1.0000,1.0000>
	    rotate <0.0000,0.0000,153.667>
	    rotate <0.0000,-162.583,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_29
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond32 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Si}
	    scale <0.564225,1.0000,1.0000>
	    rotate <0.0000,0.0000,22.8886>
	    rotate <0.0000,97.0225,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_27
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.564225,1.0000,1.0000>
	    rotate <0.0000,0.0000,202.889>
	    rotate <0.0000,97.0225,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_30
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond33 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Si}
	    scale <0.567132,1.0000,1.0000>
	    rotate <0.0000,0.0000,-40.5103>
	    rotate <0.0000,1.67456,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_27
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.567132,1.0000,1.0000>
	    rotate <0.0000,0.0000,139.49>
	    rotate <0.0000,1.67456,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_31
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond34 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.530775,1.0000,1.0000>
	    rotate <0.0000,0.0000,65.8711>
	    rotate <0.0000,-14.7247,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_5
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.530775,1.0000,1.0000>
	    rotate <0.0000,0.0000,245.871>
	    rotate <0.0000,-14.7247,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_32
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond35 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.53076,1.0000,1.0000>
	    rotate <0.0000,0.0000,-53.5354>
	    rotate <0.0000,9.18461,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_7
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.53076,1.0000,1.0000>
	    rotate <0.0000,0.0000,126.465>
	    rotate <0.0000,9.18461,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_33
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond36 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.530739,1.0000,1.0000>
	    rotate <0.0000,0.0000,-65.9592>
	    rotate <0.0000,165.469,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_8
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.530739,1.0000,1.0000>
	    rotate <0.0000,0.0000,114.041>
	    rotate <0.0000,165.469,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_34
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond37 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.530758,1.0000,1.0000>
	    rotate <0.0000,0.0000,53.6084>
	    rotate <0.0000,-170.357,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_10
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.530758,1.0000,1.0000>
	    rotate <0.0000,0.0000,233.608>
	    rotate <0.0000,-170.357,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_35
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond38 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.53079,1.0000,1.0000>
	    rotate <0.0000,0.0000,41.5343>
	    rotate <0.0000,-5.02473,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_13
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.53079,1.0000,1.0000>
	    rotate <0.0000,0.0000,221.534>
	    rotate <0.0000,-5.02473,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_36
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond39 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.550004,1.0000,1.0000>
	    rotate <0.0000,0.0000,80.1218>
	    rotate <0.0000,-38.1999,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_17
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.550004,1.0000,1.0000>
	    rotate <0.0000,0.0000,260.122>
	    rotate <0.0000,-38.1999,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_37
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond40 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.55002,1.0000,1.0000>
	    rotate <0.0000,0.0000,-12.3404>
	    rotate <0.0000,100.596,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_17
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.55002,1.0000,1.0000>
	    rotate <0.0000,0.0000,167.66>
	    rotate <0.0000,100.596,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_38
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond41 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.549989,1.0000,1.0000>
	    rotate <0.0000,0.0000,5.3625>
	    rotate <0.0000,-76.7936,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_18
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.549989,1.0000,1.0000>
	    rotate <0.0000,0.0000,185.362>
	    rotate <0.0000,-76.7936,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_39
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond42 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.549987,1.0000,1.0000>
	    rotate <0.0000,0.0000,34.9034>
	    rotate <0.0000,164.861,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_18
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.549987,1.0000,1.0000>
	    rotate <0.0000,0.0000,214.903>
	    rotate <0.0000,164.861,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_40
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond43 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Nar}
	    scale <0.497525,1.0000,1.0000>
	    rotate <0.0000,0.0000,65.9826>
	    rotate <0.0000,-171.08,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_20
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.497525,1.0000,1.0000>
	    rotate <0.0000,0.0000,245.983>
	    rotate <0.0000,-171.08,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_41
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond44 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.549997,1.0000,1.0000>
	    rotate <0.0000,0.0000,-40.125>
	    rotate <0.0000,86.94,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_21
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.549997,1.0000,1.0000>
	    rotate <0.0000,0.0000,139.875>
	    rotate <0.0000,86.94,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_42
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond45 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.550043,1.0000,1.0000>
	    rotate <0.0000,0.0000,-29.0874>
	    rotate <0.0000,-91.2875,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_21
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.550043,1.0000,1.0000>
	    rotate <0.0000,0.0000,150.913>
	    rotate <0.0000,-91.2875,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_43
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond46 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.550001,1.0000,1.0000>
	    rotate <0.0000,0.0000,17.1902>
	    rotate <0.0000,100.278,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_24
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.550001,1.0000,1.0000>
	    rotate <0.0000,0.0000,197.19>
	    rotate <0.0000,100.278,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_44
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond47 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.550021,1.0000,1.0000>
	    rotate <0.0000,0.0000,-24.8164>
	    rotate <0.0000,-78.9951,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_25
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.550021,1.0000,1.0000>
	    rotate <0.0000,0.0000,155.184>
	    rotate <0.0000,-78.9951,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_45
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond48 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.495017,1.0000,1.0000>
	    rotate <0.0000,0.0000,-83.1657>
	    rotate <0.0000,17.4353,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_29
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.495017,1.0000,1.0000>
	    rotate <0.0000,0.0000,96.8343>
	    rotate <0.0000,17.4353,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_46
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond49 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.494997,1.0000,1.0000>
	    rotate <0.0000,0.0000,5.06486>
	    rotate <0.0000,167.978,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_30
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.494997,1.0000,1.0000>
	    rotate <0.0000,0.0000,185.065>
	    rotate <0.0000,167.978,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_47
	   }
	  }
	 }

#declare Aromatic_Test_for_Open_Babel_bond50 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.495009,1.0000,1.0000>
	    rotate <0.0000,0.0000,-68.9902>
	    rotate <0.0000,-178.337,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_31
	   }
	   object {
	    bond_1
	    pigment{color Color_HC}
	    scale <0.495009,1.0000,1.0000>
	    rotate <0.0000,0.0000,111.01>
	    rotate <0.0000,-178.337,0.0000>
	    translate Aromatic_Test_for_Open_Babel_pos_48
	   }
	  }
	 }

#end // (CST-Bonds)


//All atoms of molecule Aromatic_Test_for_Open_Babel
#ifdef (TRANS)
#declare Aromatic_Test_for_Open_Babel_atoms = merge {
#else
#declare Aromatic_Test_for_Open_Babel_atoms = union {
#end //(End of TRANS)
	  object{Aromatic_Test_for_Open_Babel_atom1}
	  object{Aromatic_Test_for_Open_Babel_atom2}
	  object{Aromatic_Test_for_Open_Babel_atom3}
	  object{Aromatic_Test_for_Open_Babel_atom4}
	  object{Aromatic_Test_for_Open_Babel_atom5}
	  object{Aromatic_Test_for_Open_Babel_atom6}
	  object{Aromatic_Test_for_Open_Babel_atom7}
	  object{Aromatic_Test_for_Open_Babel_atom8}
	  object{Aromatic_Test_for_Open_Babel_atom9}
	  object{Aromatic_Test_for_Open_Babel_atom10}
	  object{Aromatic_Test_for_Open_Babel_atom11}
	  object{Aromatic_Test_for_Open_Babel_atom12}
	  object{Aromatic_Test_for_Open_Babel_atom13}
	  object{Aromatic_Test_for_Open_Babel_atom14}
	  object{Aromatic_Test_for_Open_Babel_atom15}
	  object{Aromatic_Test_for_Open_Babel_atom16}
	  object{Aromatic_Test_for_Open_Babel_atom17}
	  object{Aromatic_Test_for_Open_Babel_atom18}
	  object{Aromatic_Test_for_Open_Babel_atom19}
	  object{Aromatic_Test_for_Open_Babel_atom20}
	  object{Aromatic_Test_for_Open_Babel_atom21}
	  object{Aromatic_Test_for_Open_Babel_atom22}
	  object{Aromatic_Test_for_Open_Babel_atom23}
	  object{Aromatic_Test_for_Open_Babel_atom24}
	  object{Aromatic_Test_for_Open_Babel_atom25}
	  object{Aromatic_Test_for_Open_Babel_atom26}
	  object{Aromatic_Test_for_Open_Babel_atom27}
	  object{Aromatic_Test_for_Open_Babel_atom28}
	  object{Aromatic_Test_for_Open_Babel_atom29}
	  object{Aromatic_Test_for_Open_Babel_atom30}
	  object{Aromatic_Test_for_Open_Babel_atom31}
	  object{Aromatic_Test_for_Open_Babel_atom32}
	  object{Aromatic_Test_for_Open_Babel_atom33}
	  object{Aromatic_Test_for_Open_Babel_atom34}
	  object{Aromatic_Test_for_Open_Babel_atom35}
	  object{Aromatic_Test_for_Open_Babel_atom36}
	  object{Aromatic_Test_for_Open_Babel_atom37}
	  object{Aromatic_Test_for_Open_Babel_atom38}
	  object{Aromatic_Test_for_Open_Babel_atom39}
	  object{Aromatic_Test_for_Open_Babel_atom40}
	  object{Aromatic_Test_for_Open_Babel_atom41}
	  object{Aromatic_Test_for_Open_Babel_atom42}
	  object{Aromatic_Test_for_Open_Babel_atom43}
	  object{Aromatic_Test_for_Open_Babel_atom44}
	  object{Aromatic_Test_for_Open_Babel_atom45}
	  object{Aromatic_Test_for_Open_Babel_atom46}
	  object{Aromatic_Test_for_Open_Babel_atom47}
	  object{Aromatic_Test_for_Open_Babel_atom48}
	 }

//Bonds only needed for ball and sticks or capped sticks models
#if (BAS | CST)
#declare Aromatic_Test_for_Open_Babel_bonds = union {
	  object{Aromatic_Test_for_Open_Babel_bond0}
	  object{Aromatic_Test_for_Open_Babel_bond1}
	  object{Aromatic_Test_for_Open_Babel_bond2}
	  object{Aromatic_Test_for_Open_Babel_bond3}
	  object{Aromatic_Test_for_Open_Babel_bond4}
	  object{Aromatic_Test_for_Open_Babel_bond5}
	  object{Aromatic_Test_for_Open_Babel_bond6}
	  object{Aromatic_Test_for_Open_Babel_bond7}
	  object{Aromatic_Test_for_Open_Babel_bond8}
	  object{Aromatic_Test_for_Open_Babel_bond9}
	  object{Aromatic_Test_for_Open_Babel_bond10}
	  object{Aromatic_Test_for_Open_Babel_bond11}
	  object{Aromatic_Test_for_Open_Babel_bond12}
	  object{Aromatic_Test_for_Open_Babel_bond13}
	  object{Aromatic_Test_for_Open_Babel_bond14}
	  object{Aromatic_Test_for_Open_Babel_bond15}
	  object{Aromatic_Test_for_Open_Babel_bond16}
	  object{Aromatic_Test_for_Open_Babel_bond17}
	  object{Aromatic_Test_for_Open_Babel_bond18}
	  object{Aromatic_Test_for_Open_Babel_bond19}
	  object{Aromatic_Test_for_Open_Babel_bond20}
	  object{Aromatic_Test_for_Open_Babel_bond21}
	  object{Aromatic_Test_for_Open_Babel_bond22}
	  object{Aromatic_Test_for_Open_Babel_bond23}
	  object{Aromatic_Test_for_Open_Babel_bond24}
	  object{Aromatic_Test_for_Open_Babel_bond25}
	  object{Aromatic_Test_for_Open_Babel_bond26}
	  object{Aromatic_Test_for_Open_Babel_bond27}
	  object{Aromatic_Test_for_Open_Babel_bond28}
	  object{Aromatic_Test_for_Open_Babel_bond29}
	  object{Aromatic_Test_for_Open_Babel_bond30}
	  object{Aromatic_Test_for_Open_Babel_bond31}
	  object{Aromatic_Test_for_Open_Babel_bond32}
	  object{Aromatic_Test_for_Open_Babel_bond33}
	  object{Aromatic_Test_for_Open_Babel_bond34}
	  object{Aromatic_Test_for_Open_Babel_bond35}
	  object{Aromatic_Test_for_Open_Babel_bond36}
	  object{Aromatic_Test_for_Open_Babel_bond37}
	  object{Aromatic_Test_for_Open_Babel_bond38}
	  object{Aromatic_Test_for_Open_Babel_bond39}
	  object{Aromatic_Test_for_Open_Babel_bond40}
	  object{Aromatic_Test_for_Open_Babel_bond41}
	  object{Aromatic_Test_for_Open_Babel_bond42}
	  object{Aromatic_Test_for_Open_Babel_bond43}
	  object{Aromatic_Test_for_Open_Babel_bond44}
	  object{Aromatic_Test_for_Open_Babel_bond45}
	  object{Aromatic_Test_for_Open_Babel_bond46}
	  object{Aromatic_Test_for_Open_Babel_bond47}
	  object{Aromatic_Test_for_Open_Babel_bond48}
	  object{Aromatic_Test_for_Open_Babel_bond49}
	  object{Aromatic_Test_for_Open_Babel_bond50}
	 }
#end


//Definition of molecule Aromatic_Test_for_Open_Babel
#if (SPF)
#declare Aromatic_Test_for_Open_Babel = object{
	  Aromatic_Test_for_Open_Babel_atoms
#else
#declare Aromatic_Test_for_Open_Babel = union {
	  object{Aromatic_Test_for_Open_Babel_atoms}
#if (BAS | CST)//(Not really needed at moment!)
#if (TRANS)
	  difference {
	   object{Aromatic_Test_for_Open_Babel_bonds}
	   object{Aromatic_Test_for_Open_Babel_atoms}
	  }
#else
	  object{Aromatic_Test_for_Open_Babel_bonds}
#end //(End of TRANS)
#end //(End of (BAS|CST))
#end //(End of SPF)
//	  bounded_by {
//	   box {
//	    <-10.985,-6.2264,-4.7478>
//	    <13.0374,6.745,4.4602>
	 }

//Center of molecule Aromatic_Test_for_Open_Babel (bounding box)
#declare Aromatic_Test_for_Open_Babel_center = <-1.0262,-0.2593,0.1438>

